version: "3.8"

services:
  frontend:
    build: ./Client
    ports:
      - 3000:3000
    stdin_open: true

  backend:
    build: ./Server
    ports:
      - 4000:4000
    environment:
      DB_URL: mongodb://db/instagram

  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - instagram:/data/db

volumes:
  instagram:
